apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanout-helper
  namespace: fanout
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fanout-helper
      version: v1
  template:
    metadata:
      labels:
        app: fanout-helper
        version: v1
    spec:
      containers:
        - image: 156305373065.dkr.ecr.eu-west-1.amazonaws.com/fanout-helper:v1
          name: fanout-helper
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              port: 80
              path: /health
              scheme: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              scheme: http
              path: /helper
              port: 80
            periodSeconds: 2
            initialDelaySeconds: 3            

---
apiVersion: v1
kind: Service
metadata:
  name: fanout-helper
  namespace: fanout
  labels:
    service: fanout-helper
    version: v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fanout-helper
    version: v1
